# -*- coding: utf-8 -*-
"""usecase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_WmrAoV2BjxTcPW_O87Jpt6FVb7GjcbS
"""

import os
import subprocess

repo_url = "https://github.com/sukhdakoha/bnb-booking-system.git"
repo_name = "knowlbase"
if not os.path.exists(repo_name):
    print("Cloning the repository...")
    subprocess.run(["git", "clone", repo_url])
else:
    print("Repository already cloned.")

print("Current directory:", os.getcwd())
print("Contents of the current directory:", os.listdir())

!apt-get install git

!git clone https://github.com/sukhdakoha/bnb-booking-system.git

import os
print("Contents after cloning:", os.listdir())

repo_url = "https://github.com/sukhdakoha/bnb-booking-system.git"
repo_name = "knowlbase"

try:
    subprocess.run(["git", "--version"], check=True)
    print("Git is installed.")
except FileNotFoundError:
    print("Installing Git...")
    subprocess.run(["apt-get", "install", "git"], check=True)

if repo_name not in os.listdir():
    print("Cloning the repository...")
    result = subprocess.run(["git", "clone", repo_url], capture_output=True, text=True)
    if result.returncode == 0:
        print("Repository cloned successfully.")
    else:
        print("Error cloning repository:")
        print(result.stderr)
        exit()
else:
    print("Repository already exists.")

import os

if os.path.exists(repo_name):
    os.chdir(repo_name)
    print("Changed directory to:", os.getcwd())
else:
    print(f"Repository directory {repo_name} not found. Check cloning process.")
    exit()

print("Contents of the repository:", os.listdir())

